### ISSUE TITLE
Bot activates when toggle mute/unmute is used

### ISSUE THREAD

**Issue by SBonnietheoneandonly** [tomrosling/MalaBot#1]
This happens when the following is done:
1. be in a voice channel
2. toggle mute
![image](https://user-images.githubusercontent.com/82537274/114760030-2f8a9f80-9d5f-11eb-969b-a07a5a125275.png)
3. toggle unmute
![image](https://user-images.githubusercontent.com/82537274/114760062-3b766180-9d5f-11eb-8145-a9c0f264b805.png)
the line "[USER] moved to General Hangout." is sent in the #malabot channel
![image](https://user-images.githubusercontent.com/82537274/114760158-52b54f00-9d5f-11eb-8b4b-cda5cdf8c31b.png)
4. Repeat from 2

**Comment by tomrosling** [comment]
Thank you for the lovely bug report.
